name: "Clusters: Modify JSON Data"
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      region:
        type: string
      environment:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string
jobs:
  change:
    name: Change and Push
    runs-on: ubuntu-22.04
    steps:
    -
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    -
      name: Add new cluster
      id: clusters-add
      if: ${{ fromJson(inputs.port_payload).payload.action.trigger == 'CREATE' }}
      uses: PashmakGuru/gha-platform-orchestrator/actions/clusters-add
      with:
        config-file: clusters/clusters.json
        name: ${{ inputs.name }}
        location: ${{ inputs.region }}
        environment: ${{ inputs.environment }}
    -
      name: Delete a cluster
      id: clusters-delete
      if: ${{ fromJson(inputs.port_payload).payload.action.trigger == 'DELETE' }}
      uses: PashmakGuru/gha-platform-orchestrator/actions/clusters-delete
      with:
        config-file: clusters/clusters.json
        name: ${{ fromJson(inputs.port_payload).payload.entity.identifier }}
    -
      name: Commit & Push changes
      uses: actions-js/push@master
      with:
        message: "🅿️ Port Action: ${{ steps.clusters-add.outcome == 'success' && 'Add' || 'Delete' }} cluster '${{ steps.clusters-add.outcome == 'success' && inputs.name || fromJson(inputs.port_payload).payload.entity.identifier }}'\nTriggered by: ${{ fromJson(inputs.port_payload).trigger.by.user.firstName }} ${{ fromJson(inputs.port_payload).trigger.by.user.lastName }}"
        github_token: ${{ secrets.GH_PAT }}
