name: "Clusters: Run Terraform"
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    paths:
    - 'clusters/**'
    - '.github/workflows/clusters-sync.yaml'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - 'main'
    paths:
    - 'clusters/**'
    - '.github/workflows/clusters-sync.yaml'

env:
    TF_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
    TF_CLOUD_ORGANIZATION: ${{ vars.TFC_ORGANIZATION }}
    TF_WORKSPACE: clusters-prod

jobs:
  terraform-apply:
    name: Terraform Plan & Apply
    runs-on: ubuntu-22.04
    steps:
      -
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout source code
      -
        name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        id: upload-configuration
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: clusters
      -
        name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload-configuration.outputs.configuration_version_id }}
      -
        name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.1.1
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.create-run.outputs.payload).data.relationships.plan.data.id }}
      -
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.1.1
        if: github.ref_name == 'main'
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
